# Generated by Django 4.2.7 on 2023-11-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_alter_usuario_direccion_alter_usuario_dni_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='disponibilidad',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('prestado', 'Prestado'), ('en-proceso', 'En proceso de préstamo')], default='disponible', max_length=30),
        ),
    ]
